---
apiVersion: v1
kind: Namespace
metadata:
  name: eks-test

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
  namespace: eks-test
data:
  index.html: |
    <html>
    <h2>Hello world 1!!</h2>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  namespace: eks-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testService: service-1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-config
          mountPath: /usr/share/nginx/html
        - name: eks-test-app-volume
          mountPath: /local-volume
      volumes:
      - name: nginx-index-config
        configMap:
          name: nginx-config-1
      - name: eks-test-app-volume
        persistentVolumeClaim:
          claimName: eks-test-app-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-test
  name: nginx-deployment-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-test-app-pvc
  namespace: eks-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
